MVC/Areas/AdminPanel/Models/VMs/Report/GetMoldProductionReportVM.cs
namespace MVC.Areas.AdminPanel.Models.VMs.Report
{
    public class GetMoldProductionReportVM
    {
        public int OfferCartId { get; set; }
        public string ProductName { get; set; }
        public string MoldProductionStatus { get; set; }
    }
}

MVC/Areas/AdminPanel/Models/VMs/Report/GetPaymentReportVM.cs
namespace MVC.Areas.AdminPanel.Models.VMs.Report
{
    public class GetPaymentReportVM
    {
        public int OfferCartId { get; set; }
        public decimal TotalPrice { get; set; }
        public string PaymentStatus { get; set; }
        public DateTime? CompletedDate { get; set; }
    }
}

MVC/Areas/AdminPanel/Models/VMs/Report/GetProductAccordingToLikeVM.cs
namespace MVC.Areas.AdminPanel.Models.VMs.Report
{
    public class GetProductAccordingToLikeVM
    {
        public string ProductName { get; set; }
        public int Likes { get; set; }
    }
}

MVC/Areas/AdminPanel/Models/VMs/Report/GetProductAccordingToViewsVM.cs
namespace MVC.Areas.AdminPanel.Models.VMs.Report
{
    public class GetProductAccordingToViewsVM
    {
        public string ProductName { get; set; }
        public int Views { get; set; }
    }
}

MVC/Areas/AdminPanel/Models/VMs/Report/OfferCartMessage.cs
namespace MVC.Areas.AdminPanel.Models.VMs.Report
{
    public class OfferCartMessage
    {
    }
}

MVC/Areas/AdminPanel/Controllers/OfferCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.Areas.AdminPanel.Models.DTOs.OfferCart;
using MVC.Areas.AdminPanel.Models.VMs.OfferCart;
using MVC.Areas.AdminPanel.Models.VMs.Product;

namespace MVC.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class OfferCartController : Controller
    {
        private readonly HttpClient _httpClient;

        public OfferCartController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        string uri = "http://localhost:5211/api/OfferCart";

        public async Task<IActionResult> GetAllOfferCarts()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetAllOfferCarts");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetAllOfferCartsVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        //sipariş detayını gösterme
        public async Task<IActionResult> Details(int offerCartId)
        {
            var reponse = await _httpClient.GetAsync($"{uri}/GetOfferCartById/{offerCartId}");
            if (reponse.IsSuccessStatusCode)
            {
                var offerCart = await reponse.Content.ReadFromJsonAsync<OfferCartDTO>();
                return View(offerCart);
            }
            return NotFound();
        }
    }
}

MVC/Areas/AdminPanel/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using MVC.Areas.AdminPanel.Models.VMs;
using MVC.Areas.AdminPanel.Models.VMs.Category;
using MVC.Areas.AdminPanel.Models.VMs.Product;
using MVC.Models;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace MVC.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]

    public class ProductController : Controller
    {
        private readonly HttpClient _httpClient;


        public ProductController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        string uri = "http://localhost:5211/api";

        //Tüm ürünleri listeleme
        public async Task<IActionResult> GetAllProducts()
        {
            var response = await _httpClient.GetAsync($"{uri}/Product/GetAllProducts");
            if (response.IsSuccessStatusCode)
            {
                var products = await response.Content.ReadFromJsonAsync<IEnumerable<ListProduct>>();
                return View(products);
            }
            return NoContent();
        }


        //ürün ekleme
        public async Task<IActionResult> Create()
        {
            CreateProductVM Createvm = new CreateProductVM();
            var response = await _httpClient.GetAsync($"{uri}/Category/GetAllCategories");
            if (response.IsSuccessStatusCode)
            {
                var categories = await response.Content.ReadFromJsonAsync<List<Category>>();
                Createvm.Categories = categories.Select(x => new SelectListItem() { Text = x.CategoryName, Value = x.CategoryId.ToString() }).ToList();
            }
            var response1 = await _httpClient.GetAsync($"{uri}/Product/GetAllMaterials");
            if (response1.IsSuccessStatusCode)
            {
                var materials = await response1.Content.ReadFromJsonAsync<List<MaterialVM>>();
                Createvm.Materials = materials.Select(x => new SelectListItem() { Text = x.Name, Value = x.MaterialId.ToString() }).ToList();
            }
            return View(Createvm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductVM vm)
        {
            var response2 = await _httpClient.PostAsJsonAsync($"{uri}/Product/AddProduct", vm.AddProductDTO);
            if (response2.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Ürün başarıyla eklendi.";
                return RedirectToAction("GetAllProducts");
            }
            TempData["ErrorMessage"] = "Ürün ekleme başarısız!";
            return View(vm);

        }

        UpdateProductVM Updatevm = new UpdateProductVM();
        //ürün güncelleme
        public async Task<IActionResult> Update(int ProductId)
        {

            var response = await _httpClient.GetAsync($"{uri}/Product/GetProductById/{ProductId}");
            if (response.IsSuccessStatusCode)
            {
                var product= await response.Content.ReadFromJsonAsync<UpdateProductDTO>();
                Updatevm.UpdateProductDTO = product;
            }
            var response1 = await _httpClient.GetAsync($"{uri}/Category/GetAllCategories");
            if (response1.IsSuccessStatusCode)
            {
                var categories = await response1.Content.ReadFromJsonAsync<List<Category>>();
                Updatevm.Categories = categories.Select(x => new SelectListItem() { Text = x.CategoryName, Value = x.CategoryId.ToString() }).ToList();
            }
            var response2 = await _httpClient.GetAsync($"{uri}/Product/GetAllMaterials");
            if (response2.IsSuccessStatusCode)
            {
                var materials = await response2.Content.ReadFromJsonAsync<List<MaterialVM>>();
                Updatevm.Materials = materials.Select(x => new SelectListItem() { Text = x.Name, Value = x.MaterialId.ToString() }).ToList();
            }

            Updatevm.UpdateProductDTO.ProductId = ProductId;
            return View(Updatevm);
        }


        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductVM vm)
        {

            var response3 = await _httpClient.PutAsJsonAsync($"{uri}/Product/UpdateProduct", vm.UpdateProductDTO);
            if (response3.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Ürün başarıyla güncellendi.";
                return RedirectToAction("GetAllProducts");
            }
            TempData["ErrorMessage"] = "Güncelleme başarısız!";
            return View(vm);
        }


        //ürün pasif etme(silme)
        public async Task<IActionResult> Delete(int ProductId)
        {
            var response = await _httpClient.DeleteAsync($"{uri}/Product/DeleteProduct/{ProductId}");
            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Ürün başarıyla silindi.";
                return RedirectToAction("GetAllProducts");
            }
            return NotFound();
        }


        //Ürün aktif etme(metodunu repo-servise-api'de yazman lazım.Sonra burada oluştur)
        public async Task<IActionResult> ActiveProduct(int ProductId)
        {
            var response = await _httpClient.GetAsync($"{uri}/Product/MakeProductActive/{ProductId}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAllProducts");
            }
            return NotFound();
        }


        //ürün detayını gösterme
        public async Task<IActionResult> Details(int ProductId)
        {
            var reponse = await _httpClient.GetAsync($"{uri}/Product/GetProductById/{ProductId}");
            if (reponse.IsSuccessStatusCode)
            {
                var product = await reponse.Content.ReadFromJsonAsync<GetProductDetailsVM>();
                return View(product);
            }
            return NotFound();
        }




        //Arama motorundaki kelimeye göre kategroileri bulup getirme
        public async Task<IActionResult> SearchCategoryByKeyword(string keyword)
        {
            var response = await _httpClient.GetAsync($"{uri}/Product/{keyword}");
            if (response.IsSuccessStatusCode)
            {
                var products = await response.Content.ReadFromJsonAsync<List<AddProductDTO>>();
                return View(products);
            }
            return NotFound();
        }


        //***************************************************************


        //yeni resim ekleme deneme metodu
        public async Task<IActionResult> UpdateProductImage(int productId)
        {
            var response = await _httpClient.GetAsync($"{uri}/Product/FindProduct/{productId}");
            if (response.IsSuccessStatusCode)
            {
                var product = await response.Content.ReadAsStringAsync();
                bool productExists = bool.Parse(product);

                if (productExists)
                {
                    var vm = new UploadProductImageVM
                    {
                        ProductId = productId
                    };
                    return View(vm);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductImage(UploadProductImageVM vm)
        {
            if (vm.Files == null || !vm.Files.Any())
            {
                TempData["ErrorMessage"] = "Lütfen en az bir resim dosyası seçin!";
                return View(vm);
            }

            List<string> uploadedImageUrls = new List<string>();

            // Her dosya için işlemi gerçekleştir
            foreach (var file in vm.Files)
            {
                if (file.Length > 0)
                {
                    string path = Path.Combine("wwwroot/images", file.FileName);
                    using (FileStream fs = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(fs);
                    }

                    uploadedImageUrls.Add(file.FileName); // Yüklenen resim URL'sini listeye ekle
                }
            }

            // UploadImage nesnesini oluştur ve API'ye gönder
            UploadImage uploadImage = new UploadImage
            {
                ProductId = vm.ProductId,
                ImageUrls = uploadedImageUrls // Birden fazla URL'yi liste olarak API'ye gönder
            };

            var response = await _httpClient.PostAsJsonAsync($"{uri}/Product/UpdateProductImage", uploadImage); // API'ye çoklu resimleri gönder
            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Resimler başarıyla yüklendi!";
                return RedirectToAction("GetAllProducts");
            }

            TempData["ErrorMessage"] = "Resim yükleme başarısız oldu.";
            return View(vm);

        }

        //[HttpPost]
        //public async Task<IActionResult> UpdateProductImage(UploadProductImageVM vm)
        //{

        //    if (vm.File == null || vm.File.Length == 0)
        //    {
        //        TempData["ErrorMessage"] = "Lütfen bir resim dosyası seçin!";
        //        return View(vm);
        //    }
        //    string path = "wwwroot/images/" + vm.File.FileName;
        //    FileStream fs = new FileStream(path, FileMode.Create);
        //    await vm.File.CopyToAsync(fs);
        //    fs.Close();

        //    UploadImage uploadImage = new UploadImage();
        //    uploadImage.ProductId = vm.ProductId;
        //    uploadImage.ImageUrl = vm.File.FileName;
        //    var response = await _httpClient.PostAsJsonAsync($"{uri}/Product/UpdateProductImage", uploadImage);
        //    if (response.IsSuccessStatusCode)
        //    {
        //        TempData["SuccessMessage"] = "Resim başarıyla yüklendi!";
        //        return RedirectToAction("GetAllProducts");
        //    }

MVC/Areas/AdminPanel/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.Areas.AdminPanel.Models.VMs.Report;
using MVC.Areas.ContentManagerPanel.Models.DTOs.Blog;

namespace MVC.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class ReportController : Controller
    {
        private readonly HttpClient _httpClient;

        public ReportController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        string uri = "http://localhost:5211/api/Report";
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetOfferCartSummaryReport(DateTime startDate, DateTime endDate)
        {
            var response = await _httpClient.GetAsync($"{uri}/GetOfferCartSummaryReport?startDate={startDate.ToString("yyyy-MM-dd")}&endDate={endDate.ToString("yyyy-MM-dd")}");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetOfferCartSummaryReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetUserActivityReport(int userId)
        {
            var response = await _httpClient.GetAsync($"{uri}/GetUserActivityReport/{userId}");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetUserActivityReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetProductOfferStatusReport()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetProductOfferStatusReport");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetProductOfferStatusReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetApprovedOfferCartReport(DateTime startDate, DateTime endDate)
        {
            var response = await _httpClient.GetAsync($"{uri}/GetApprovedOfferCartReport?startDate={startDate.ToString("yyyy-MM-dd")}&endDate={endDate.ToString("yyyy-MM-dd")}");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetOfferCartSummaryReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetPaymentReport()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetPaymentReport");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetPaymentReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetRejectedOffersReport()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetRejectedOffersReport");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetRejectedOffersReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetMoldProductionReport()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetMoldProductionReport");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetMoldProductionReportVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetProductAccordingToLike()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetProductAccordingToLike");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetProductAccordingToLikeVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

        public async Task<IActionResult> GetProductAccordingToViews()
        {
            var response = await _httpClient.GetAsync($"{uri}/GetProductAccordingToViews");
            if (response.IsSuccessStatusCode)
            {
                var offerCarts = await response.Content.ReadFromJsonAsync<List<GetProductAccordingToViewsVM>>();
                return View(offerCarts);
            }
            return NoContent();
        }

    }
}

MVC/Areas/AdminPanel/Views/Report/GetApprovedOfferCartReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetOfferCartSummaryReportVM>

@{
    ViewData["Title"] = "Get Offer Cart Summary Report";
}

<h1>Get Offer Cart Summary Report</h1>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Offer Cart ID
                </th>
                <th>
                    Customer ID
                </th>
                <th>
                    Product ID
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    Total Price
                </th>
                <th>
                    Completed Date
                </th>
                <th>
                    Added Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OfferCartId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AppUserId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CompletedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddedDate)
                    </td>
                    <td>
                        <a class="btn btn-light" asp-action="Details" asp-controller="OfferCart" asp-area="AdminPanel" asp-route-offerCartId="@item.OfferCartId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Veri bulunamadı.</p>
}

MVC/Areas/AdminPanel/Views/Report/GetMoldProductionReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetMoldProductionReportVM>

@{
    ViewData["Title"] = "GetMoldProductionReport";
}

<h1>Get Mold Production Report</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                OfferCart ID
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                Mold Production Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OfferCartId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MoldProductionStatus)
                </td>
                <td>
                    <a class="btn btn-light" asp-action="Details" asp-controller="OfferCart" asp-area="AdminPanel" asp-route-offerCartId="@item.OfferCartId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC/Areas/AdminPanel/Views/Report/GetOfferCartSummaryReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetOfferCartSummaryReportVM>

@{
    ViewData["Title"] = "Get Offer Cart Summary Report";
}

<h1>Get Offer Cart Summary Report</h1>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Offer Cart ID
                </th>
                <th>
                    Customer ID
                </th>
                <th>
                    Product ID
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    Total Price
                </th>
                <th>
                    Completed Date
                </th>
                <th>
                    Added Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OfferCartId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AppUserId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CompletedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddedDate)
                    </td>
                    <td>
                        <a class="btn btn-light" asp-action="Details" asp-controller="OfferCart" asp-area="AdminPanel" asp-route-offerCartId="@item.OfferCartId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Veri bulunamadı.</p>
}

MVC/Areas/AdminPanel/Views/Report/GetPaymentReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetPaymentReportVM>

@{
    ViewData["Title"] = "GetPaymentReport";
}

<h1>Get Payment Report</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Offer Cart ID
            </th>
            <th>
                Total Price
            </th>
            <th>
                Payment Status
            </th>
            <th>
                Completed Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OfferCartId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletedDate)
                </td>
                <td>
                    <a class="btn btn-light" asp-action="Details" asp-controller="OfferCart" asp-area="AdminPanel" asp-route-offerCartId="@item.OfferCartId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC/Areas/AdminPanel/Views/Report/GetProductAccordingToLike.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetProductAccordingToLikeVM>

@{
    ViewData["Title"] = "GetProductAccordingToLike";
}

<h1>Get Product According To Like</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Likes)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Likes)
                </td>
            </tr>
        }
    </tbody>
</table>

MVC/Areas/AdminPanel/Views/Report/GetProductOfferStatusReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetProductOfferStatusReportVM>

@{
    ViewData["Title"] = "GetProductOfferStatusReport";
}

<h1>Get Product Offer Status Report</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Product ID
            </th>
            <th>
                Customer
            </th>
            <th>
                Product
            </th>
            <th>
                Price
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OfferStatus)
                </td>
                <td>
                    <a class="btn btn-light" asp-action="Details" asp-controller="Product" asp-area="AdminPanel" asp-route-offerCartId="@item.ProductId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC/Areas/AdminPanel/Views/Report/GetRejectedOffersReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetRejectedOffersReportVM>

@{
    ViewData["Title"] = "GetRejectedOffersReport";
}

<h1>Get Rejected Offers Report</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OfferCartId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AddedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RejectionReason)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OfferCartId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RejectionReason)
                </td>
                <td>
                    <a class="btn btn-light" asp-action="Details" asp-controller="OfferCart" asp-area="AdminPanel" asp-route-offerCartId="@item.OfferCartId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC/Areas/AdminPanel/Views/Report/GetUserActivityReport.cshtml
@model IEnumerable<MVC.Areas.AdminPanel.Models.VMs.Report.GetUserActivityReportVM>

@{
    ViewData["Title"] = "GetUserActivityReport";
}

<h1>Get User Activity Report</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Offer Cart ID
            </th>
            <th>
                Customer ID
            </th>
            <th>
                Product ID
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                Total Price
            </th>
            <th>
                Completed Date
            </th>
            <th>
                Added Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OfferCartId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AppUserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddedDate)
                </td>
                <td>
                    <a class="btn btn-light" asp-action="Details" asp-controller="OfferCart" asp-area="AdminPanel" asp-route-offerCartId="@item.OfferCartId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>